apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: bucketaccess
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    crossplane.io/xrd: xbucketaccessinstances.skip.kartverket.no
    provider: gcp
spec:
  writeConnectionSecretsToNamespace: upbound-system
  compositeTypeRef:
    apiVersion: skip.kartverket.no/v1alpha1
    kind: XBucketAccessInstance
  resources:
  - name: bucketiam
    base:
      apiVersion: storage.gcp.upbound.io/v1beta1
      kind: BucketIAMMember
      spec:
        forProvider:
          member:
          role: roles/storage.admin
          bucket:
        providerConfigRef:
          name: 
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.accessTo.gcpServiceAccount
      toFieldPath: spec.forProvider.member
      transforms:
      - type: string
        string:
          type: Format
          fmt: "serviceAccount:%s"
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.accessTo.bucketName
      toFieldPath: spec.forProvider.bucket
    - type: PatchSet
      patchSetName: providerConfig

  - name: serviceaccountwifiam
    base:
      apiVersion: cloudplatform.gcp.upbound.io/v1beta1
      kind: ServiceAccountIAMMember
      spec:
        forProvider:
          member:
          role: roles/iam.workloadIdentityUser
          serviceAccountId:
        providerConfigRef:
          name: 
    patches:
    - type: CombineFromComposite
      combine:
        variables:
        - fromFieldPath: spec.parameters.accessFrom.gcpKubernetesProject
        - fromFieldPath: spec.claimRef.namespace
        - fromFieldPath: spec.parameters.accessFrom.kubernetesServiceAccount
        strategy: string
        string:
          fmt: "serviceAccount:%s.svc.id.goog[%s/%s]"
      toFieldPath: spec.forProvider.member
      policy:
        fromFieldPath: Required
    - type: CombineFromComposite
      combine:
        variables:
        - fromFieldPath: spec.parameters.accessTo.gcpProject
        - fromFieldPath: spec.parameters.accessTo.gcpServiceAccount
        strategy: string
        string:
          fmt: "projects/%s/serviceAccounts/%s"
      toFieldPath: spec.forProvider.serviceAccountId
      policy:
        fromFieldPath: Required
    - type: PatchSet
      patchSetName: providerConfig

  patchSets:
  - name: providerConfig
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.claimRef.namespace
      toFieldPath: spec.providerConfigRef.name
      transforms:
      - type: string
        string:
          type: Regexp
          regexp:
            match: '^(\w+)-.*'
            group: 1
