apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-terraform
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  package: xpkg.upbound.io/upbound/provider-terraform:v0.7.0
