apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xserviceaccountinstances.skip.kartverket.no
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  group: skip.kartverket.no
  names:
    kind: XServiceAccountInstance
    plural: xserviceaccountinstances
  claimNames:
    kind: ServiceAccountInstance
    plural: serviceaccountinstances
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    name:
                      type: string
                    displayName:
                      type: string
                  required:
                    - name
              required:
                - parameters
