apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: serviceaccount
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    crossplane.io/xrd: xserviceaccountinstances.skip.kartverket.no
    provider: gcp
spec:
  writeConnectionSecretsToNamespace: upbound-system
  compositeTypeRef:
    apiVersion: skip.kartverket.no/v1alpha1
    kind: XServiceAccountInstance
  resources:
    - name: serviceaccount
      base:
        apiVersion: cloudplatform.gcp.upbound.io/v1beta1
        kind: ServiceAccount
        metadata:
          name:
        spec:
          forProvider:
            displayName:
          providerConfigRef:
            name:
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.serviceAccount.displayName
          toFieldPath: spec.forProvider.displayName
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.name
          toFieldPath: metadata.name
        - type: PatchSet
          patchSetName: providerConfig

  patchSets:
    - name: providerConfig
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.claimRef.namespace
          toFieldPath: spec.providerConfigRef.name
          transforms:
            - type: string
              string:
                type: Regexp
                regexp:
                  match: '^(\w+)-.*'
                  group: 1
